class Data:
    teams_list = [
    ["Aston Villa","inglesa"],
    ["Ajax","holandesa"],
    ["Alkmaar", "holandesa"],
    ["Atlético","española"],
    ["Angers","francesa"],
    ["Athletic Club","española"],
    ["Barcelona","española"],
    ["Bayern", "alemana"],
    ["Benfica","portuguesa"],
    ["Betis	","española"],
    ["Braga","portuguesa"],
    ["Brighton","inglesa"],
    ["Brentford","inglesa"],
    ["Boavista","portuguesa"],
    ["Bologna","italiana"],
    ["Chelsea","inglesa"],
    ["CSKA Moskva","rusa"],
    ["Dortmund","alemana"],
    ["Dynamo Kyiv","rusa"],
    ["Empoli","italiana"],
    ["Estoril","portuguesa"],
    ["Everton","inglesa"],
    ["Feyenoord", "holandesa"],
    ["Fiorentina","italiana"],
    ["Freiburg","alemana"],
    ["Gil Vicente","portuguesa"],
    ["Groningen", "holandesa"],
    ["Internazionale","italiana"],
    ["Juventus","italiana"],
    ["Köln", "alemana"],
    ["Krasnodar","rusa"],
    ["Krylya Sovetov","rusa"],
    ["Heerenveen", "holandesa"],
    ["Lazio","italiana"],
    ["Leverkusen", "alemana"],
    ["Leipzig","alemana"],
    ["Lens","francesa"],
    ["Liverpool","inglesa"],
    ["Lorient","francesa"],
    ["Lokomotiv Moskva","rusa"],
    ["Lyon","francesa"],
    ["LOSC","francesa"],
    ["Marseille","francesa"],
    ["Mönchengladbach","alemana"],
    ["Monaco","francesa"],
    ["Mainz","alemana"],
    ["Man. City","inglesa"],
    ["Man. United","inglesa"],
    ["Milan","italiana"],
    ["Nantes","francesa"],
    ["Nice","francesa"],
    ["Nizhny Novgorod","rusa"],
    ["Napoli","italiana"],
    ["Osasuna","española"],
    ["Paris","francesa"],
    ["PSV","holandesa"],
    ["Porto","portuguesa"],
    ["Portimonense","portuguesa"],
    ["Rayo Vallecano","española"],
    ["Real Madrid","española"],
    ["Real Sociedad","española"],
    ["Roma","italiana"],
    ["Rubin","rusa"],
    ["Sevilla","española"],
    ["Spartak Moskva","rusa"],
    ["Sochi","rusa"],
    ["Sporting CP","portuguesa"],
    ["Twente", "holandesa"],
    ["Tottenham","inglesa"],
    ["Tondela","portuguesa"],
    ["Union Berlin","alemana"],
    ["Utrecht", "holandesa"],
    ["Valencia","española"],
    ["Vitesse","holandesa"],
    ["Vitória SC","portuguesa"],
    ["Wolfsburg","alemana"],
    ["West Ham","inglesa"],
    ["Zenit","rusa"],
    ["Zwolle", "holandesa"],
    ]

